@baseUrl = http://localhost:3000
@email = test@example.com
@password = password
@authToken = {{login.response.headers.Authorization}}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "user": {
    "email": "{{email}}",
    "password": "{{password}}"
  }
}

### Logout
DELETE {{baseUrl}}/auth/logout
Authorization: {{authToken}}
Accept: application/json

### Me
# @name me
GET {{baseUrl}}/auth/me
Authorization: {{authToken}}
Accept: application/json


### List Jobs
# @name listJobs
GET {{baseUrl}}/jobs?search=developer



################################################################################
### Admin
################################################################################

### List Jobs
# @name listJobsAdmin
GET {{baseUrl}}/admin/jobs?search=manager&page=1
Authorization: {{authToken}}
Accept: application/json


### Create Job
# @name createJobAdmin
POST {{baseUrl}}/admin/jobs
Authorization: {{authToken}}
Accept: application/json
Content-Type: application/json

{
  "job": {
    "title": "Titulo do trabalho",
    "description": "Descrição do trabalho. Minimo de 30 caracteres.",
    "employment_type": "clt",
    "location": "Local do trabalho",
    "publish_at": "2024-01-01T12:00:00Z"
  }
}

### Update Job
# @name updateJobAdmin
PUT {{baseUrl}}/admin/jobs/{{createJobAdmin.response.body.id}}
Authorization: {{authToken}}
Accept: application/json
Content-Type: application/json

{
  "job": {
    "title": "Titulo do trabalho",
    "description": "Descrição do trabalho. Minimo de 30 caracteres.",
    "employment_type": "clt",
    "location": "Local do trabalho",
    "publish_at": "2024-01-01T12:00:00Z"
  }
}

### Delete Job
# @name deleteJobAdmin
DELETE {{baseUrl}}/admin/jobs/{{createJobAdmin.response.body.id}}
Authorization: {{authToken}}
Accept: application/json

### Show Job
# @name showJobAdmin
GET {{baseUrl}}/admin/jobs/{{createJobAdmin.response.body.id}}
Authorization: {{authToken}}
Accept: application/json