@baseUrl = http://localhost:3000
@email = test@example.com
@password = password
@authToken = {{login.response.headers.Authorization}}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "user": {
    "email": "{{email}}",
    "password": "{{password}}"
  }
}

### Logout
DELETE {{baseUrl}}/auth/logout
Authorization: {{authToken}}
Accept: application/json

### Me
# @name me
GET {{baseUrl}}/auth/me
Authorization: {{authToken}}
Accept: application/json

### Create Job
# @name createJob
POST {{baseUrl}}/jobs
Authorization: {{authToken}}
Accept: application/json
Content-Type: application/json

{
  "job": {
    "title": "Titulo do trabalho",
    "description": "Descrição do trabalho. Minimo de 30 caracteres.",
    "employment_type": "clt",
    "location": "Local do trabalho",
    "status": "published"
  }
}

### List Jobs
# @name listJobs
GET {{baseUrl}}/jobs
